name: Update Recent Blogs to README
on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * 1" # Runs every week, At 00:00 on Monday.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-latest-blogs:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://www.gitpod.io/blog/rss.xml
          readme-section: feed
          empty-commits: "false"
          path: "profile/README.md"
